name: docker
services:
  web: true
  database: false
  monitoring: false
config:
  app_name: ""
  app_repo: ""
  app_branch: ""
  nodejs_version: ""
  app_port: ""
  deploy_user: root
  timezone: ""
servers:
  - name: test-web-01
    ip: 127.0.0.1
    port: 2222
    ssh_user: root
    ssh_key_path: /home/basthook/.ssh/boiler_test_rsa
    type: web
    ansible_become: true
    app_port: 3000
    http_port: 8080
    git_repo: https://github.com/Bastiblast/portefolio
    git_branch: main
    node_version: "20"
  - name: test-web-02
    ip: 127.0.0.1
    port: 2223
    ssh_user: root
    ssh_key_path: /home/basthook/.ssh/boiler_test_rsa
    type: web
    ansible_become: true
    app_port: 3001
    http_port: 8081
    git_repo: https://github.com/Bastiblast/portefolio
    git_branch: main
    node_version: "20"
  - name: test-web-03
    ip: 127.0.0.1
    port: 2224
    ssh_user: root
    ssh_key_path: /home/basthook/.ssh/boiler_test_rsa
    type: web
    ansible_become: true
    app_port: 3002
    http_port: 8082
    git_repo: https://github.com/Bastiblast/portefolio
    git_branch: main
    node_version: "20"
mono_server: false
mono_ip: 127.0.0.1
mono_ssh_key: true
