name: docker
services:
    web: true
    database: false
    monitoring: false
config:
    app_name: ""
    app_repo: ""
    app_branch: ""
    nodejs_version: ""
    app_port: ""
    deploy_user: root
    timezone: ""
servers:
    - name: docker-web-01
      ip: 127.0.0.1
      port: 2222
      ssh_user: root
      ssh_key_path: ~/.ssh/boiler_test_rsa
      type: web
      ansible_become: true
      app_port: 3000
      git_repo: https://github.com/Bastiblast/portefolio
      git_branch: main
      node_version: "20"
mono_server: true
mono_ip: 172.17.0.2
mono_ssh_key: true
mono_ssh_key_path: ~/.ssh/docker
