name: bast
services:
    web: true
    database: true
    monitoring: true
config:
    app_name: ""
    app_repo: ""
    app_branch: ""
    nodejs_version: ""
    app_port: ""
    deploy_user: root
    timezone: Europe/Paris
servers:
    - name: bast-web-01
      ip: 72.61.146.126
      port: 22
      ssh_user: root
      ssh_key_path: ~/.ssh/Hostinger
      type: web
      ansible_become: true
      app_port: 3000
      git_repo: https://github.com/Bastiblast/portefolio.git
      git_branch: main
      node_version: "20"
mono_server: true
mono_ip: 127.0.0.1
mono_ssh_key: true
mono_ssh_key_path: ~/.ssh/Hostinger.pub
