---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: enable_firewall | default(true)

- name: restart sshd
  service:
    name: ssh
    state: restarted
  ignore_errors: yes  # Ignore errors for containerized environments without service management
